config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :items, only: [:index]
  resources :favourites, only: [:create, :destroy]

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users, only: [:show]

  resources :items, only: [:show, :index, :new, :create, :destroy] do
    resources :transactions, only: [:create]
  end

  resources :transactions, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :cover
  has_many :favourites
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favourites
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favourites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def create
    @favourite = Favourite.new
    item = Item.find(params[:item_id])
    @favourite.item = item
    @favourite.user = current_user
    if @favourite.save
      respond_to do |format|
        format.json
      end
    end
  end

  def destroy
    @favourite = Favourite.where(user_id: current_user.id, item_id: params[:id]).first
    @favourite.destroy
    respond_to do |format|
      format.json
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @items = Item.all
    if params[:category].present?
      @category = Category.find_by("name ILIKE :name", name: params[:category])
      @items = @items.where(category: @category)
    end

    if params[:query].present?
      sql_query = <<~SQL
        items.name @@ :query
        OR items.description @@ :query
        OR categories.name @@ :query
      SQL
      @items = @items.joins(:category).where(sql_query, query: params[:query])
    end
  end

  def show
    @item = Item.find(params[:id])
    # more logic needed?
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(items_params)
    if current_user
      @item.user = current_user
      if @item.save
        redirect_to user_path(current_user)
      else
        render :new, status: 422
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to user_path, notice: 'Item was successfully deleted.'
  end
  private

  def items_params
    params.require(:item).permit(:name, :description, :price, :category_id, :cover)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @categories = ["Shoes", "Shirts", "Hats", "Dresses", ""]
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.where(user: current_user)
  end

  def create
    @transaction = Transaction.new
    @transaction.user = current_user
    item = Item.find(params[:item_id])
    @transaction.item = item
    @transaction.price = item.price
    if @transaction.save!
      redirect_to transactions_path
    else
      redirect_to item_path(item)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_item-card.html.erb
<div class="card" style="width: 18rem;" class="container-fluid" data-controller="favourites">
  <% if current_user && current_user.favourites.pluck(:item_id).include?(item.id) %>
    <% user_favourite_item = item.favourites.find_by(user_id: current_user.id) %>
    <%= link_to '<i class="fa-solid fa-heart fa-xl"></i>'.html_safe, favourite_path(user_favourite_item, item_id: item.id), data:{ turbo_method: :delete, item_id: item.id, action: 'click->favourites#deleteFavourite'} %>
  <% else %>
    <%= link_to '<i class="fa-regular fa-heart fa-xl"></i>'.html_safe, favourites_path({ item_id: item.id }), data: { turbo_method: :post, item_id: item.id, action: 'click->favourites#addFavourite'} %>
  <% end %>
  <% source = item.cover.attached? ? rails_blob_url(item.cover) : "https://media.istockphoto.com/id/1257563298/photo/fashion-clothes-on-a-rack-in-a-light-background-indoors-place-for-text.jpg?s=612x612&w=0&k=20&c=UTL3KlMvLkteLe_9l3QbMklBcyaKQM5j6mcDxxtTr4Y="%>
  <img class="card-img-top" src=<%=source%> alt="Clothing Image">
  <div class="card-body">
    <h4 class="item-title"><%= item.name %></h4>
    <p class="item-text"><%= item.description %></p>

    <%= link_to "View", item_path(item), class: "btn-main"%>
    <% if params[:controller] == "users" && params[:action] == "show" %>
      <%= link_to item_path(item, user_id: params[:id]), data: {turbo_method: :delete}, class: "trash" do %>
        <i class="fa-solid fa-trash fa-xl"></i>
        <% end %>
      <% end %>
     <p class="price"><%= number_with_precision(item.price, precision: 2, strip_insignificant_zeros: true)%> €</p>
  </div>
</div>

app/views/items/index.html.erb
<div class="container mt-3">
  <% if @category %>
    <h3>Category: <%= @category.name %></h3>
  <% end %>

  <div class="row gx-5 gy-5">
    <% if @items.any? %>
      <% if params[:query] %>
        <h3>Your search results:</h3>
      <% end %>
      <% @items.each do |item| %>
        <div class="col-lg-3">
          <%= render "items/item-card", item: item %>
        </div>
      <% end %>
    <% else %>
      <h3>No items found</h3>
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="upload-item-container">
  <%= simple_form_for @item do |f| %>
    <h2 class="header-create-form">Upload new product</h2>
    <div class="upload-item-form">
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.association :category %>
      <%= f.input :cover, as: :file %>
      <%= f.submit class:"btn-main btn-create-item" %>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="main-container">
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <!-- Container 1 -->
      <div class="item-image-container">

        <%= cl_image_tag @item.cover.key, class: "item-image-large" %>

      </div>
    </div>

    <!-- Container 2 -->
    <div class="col-lg-4">
      <div class="selected_item_container">
        <h2><%= @item.name %></h2>
        <h3><%= number_with_precision(@item.price, precision: 2, strip_insignificant_zeros: true)%>€</h3>
          <p>
          <%= @item.description %>
            <%# BRAND: Gucci <br>
            COLOUR: Ivory <br>
            SIZE: M <br> %>
           <%# DESCRIPTION: Warm, new, worn few times, must-have! %>
          </p>

        <!-- Content goes here -->
        <div class="buttons">
          <%= button_to "Buy", item_transactions_path(@item), class:"btn-main" %>
          <a href="" class="btn-secondary">Add to Favourites <i class="fa-solid fa-heart fa"></i> </a>
        </div>
      </div>
      <div class="seller_profile_container">




        <img src="<%= image_path('https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1556048247/ymehhwjerbyrghdubep5.jpg') %>" alt="avatar" class="profile-avatar">
        <h2><%= "Sandra" %></h2>

        <i class="fas fa-map-pin"></i>
        <p>Barcelona</p>

        <!-- Content goes here -->
      </div>

    </div>
  </div>
  </div>
</div>




<!-- Container 4 -->

  <h2>More clothes from Sandra:</h2>
  <section class="cards container-fluid">
    <div class= "container-fluid">
      <div class="row gx-5 gy-5">
        <% Item.all.each do |item|%>
          <div class="col-lg-3">
            <%= render "items/item-card", item: item %>
          </div>
        <% end %>
      </div>
    </div>
  </section>
<!-- Container 5 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recloset</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <div class="content-container overflow-hidden"><%= yield %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
       </div>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
  <section class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_url("clothes_header.jpg") %>);">
    <div>
      <h1>ReCloset</h1>
      <h3>Revamp your Closet, Fashion for Everyone </h3>
    </div>
  </section>

  <section class="container-fluid" class="categories">
    <h3 class="section-header">Browse Products by Category</h3>
    <div class="row">
      <% Category.all.each do |category| %>
        <%= link_to items_path(category: category.name), class:"col-lg-2 d-block" do %>
            <div class="rectangle">
            <p class="category-names"><%= category.name %></p>
            </div>
          <% end %>
        <% end %>
    </div>
  </section>

  <section class="cards container-fluid">
    <h3 class="section-header">New Products</h3>
    <div class= "container-fluid">
      <div class="row gx-5 gy-5">
        <% Item.first(12).each do |item|%>
          <div class="col-lg-3">
            <%= render "items/item-card", item: item %>
          </div>
        <% end %>
      </div>
    </div>
  </section>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar-recloset">
  <div class="d-flex">
    <%= link_to "ReCloset", root_path, class: "navbar-logo"  %>
    <div class="navbar-options d-flex align-items-center justify-content-between">
      <a class="nav-link dropdown-toggle ms-5" href="#" id="navbarDropdownTest" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        CATEGORIES
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownTest">
        <% Category.all.each do |category| %>
          <%= link_to category.name, items_path(category: category.name), class:"dropdown-item" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: items_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for items"
        %>
    <%= button_tag :class => "btn btn-light" do %> <i class="fas fa-search" style='color:#91a7d9'></i>
    <% end %>
    <% end %>
  </div>
  </div>


  <div class="d-flex align-items-center p-2 ">
    <% if user_signed_in? %>
    <i class="fas fa-bell text-white"></i>
      <span class="badge rounded-pill badge-notification bg-secondary">1</span>
      <%#= link_to current_user.username, "#", class:"p-2"%>
      <div class="nav-item dropdown p-2">
        <p class= "avatar dropdown-toggle " data-bs-toggle= "dropdown" aria-haspopup= 'true' aria-expanded='false' id="navbarDropdown"><%= current_user.username %></p>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Orders", transactions_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete } ,class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <%= link_to "LOGIN", new_user_session_path %>
    <% end %>
  </div>
</nav>

app/views/transactions/index.html.erb
<div class="modal-container">
  <h3 class="transactions-header">My orders</h3>

<div class="surrounding-container">
  <% @transactions.each do |transaction| %>
    <div class="card-product">
      <%= cl_image_tag transaction.item.cover.key, crop:"fill", width: 200 %>
        <div class="component-wrapper">
          <div class="card-and-trans-wrapper">
            <div class="card-product-infos">
              <h4><%= transaction.item.name %></h4>
              <p><%= transaction.item.description %></p>
              <p class="transaction-price"><%= number_with_precision(transaction.item.price, precision: 2, strip_insignificant_zeros: true) %>€</p>
            </div>
            <div class="card-product-status">
              <p>ORDER CONFIRMED</p>
            </div>
          </div>
          <div class="order-details-container">
            <!-- Button trigger modal -->
            <!-- type="button" -->
            <a id="btn-order-details" class="btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
              View order details
            </a>
          </div>
        </div>
      </div>
  <% end %>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Order details</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <strong><p>Your order has been confirmed!</p></strong>
        <p>You will receive a confirmation email with tracking information once your order has been dispatched.</p>
        <br>
        <p><strong>Shipping details</p></strong>
        <p>Please allow 5-7 business days for your package to arrive. You will receive a confirmation email with tracking information once your order has been dispatched.
        </p>
      </div>
      <div class="modal-footer">
        <button class="btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container emp-profile">
                <div class="row">
                  <div class="col-md-10 d-flex align-items-center">
                    <%= image_tag "https://kitt.lewagon.com/placeholder/users/sarahlafer", class: "avatar", alt: "avatar" %>
                    <h3 class="profile-username"><%= @user.username %></h3>
                  </div>
                  <div class="col-md-2">
                    <%= link_to "Add item", new_item_path , class:"btn-main" %>
                  </div>
                </div>
                <div class="row">

                    <div class="col-md-12">
                        <div class="profile-head">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#myitems" role="tab" aria-controls="myitems" aria-selected="false">My items</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#favourites" role="tab" aria-controls="favourites" aria-selected="false">Favourites</a>
                                </li>

                            </ul>
                        </div>
                    </div>

                </div>
                <div class="row">

                    <div class="col-md-12">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Username:</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.username%></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>First name:</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.first_name %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Last name:</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.last_name %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email:</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p><%= @user.email %></p>
                                            </div>
                                        </div>
                                            <div class="row">
                                            <div class="col-md-6">
                                            <%= link_to "Edit profile", edit_user_registration_path, class:"btn-secondary" %>
                                            </div>
                                            <div class="col-md-6">
                                                <p></p>
                                            </div>
                                        </div>
                            </div>
                            <div class="tab-pane fade" id="myitems" role="tabpanel" aria-labelledby="profile-tab">
                                            <div class="row">
                                              <% Item.where(user: @user).each do |item|%>
                                                <div class="col-lg-3">
                                                  <%= render "items/item-card", item: item %>

                                                </div>
                                              <% end %>
                                            </div>
                            </div>
                                <div class="tab-pane fade" id="favourites" role="tabpanel" aria-labelledby="profile-tab">
                                             <div class="row">
                                              <% @user.favourites.each do |favourite|%>
                                                <div class="col-lg-3">
                                                  <%= render "items/item-card", item: favourite.item %>
                                                </div>
                                              <% end %>
                                            </div>
                        </div>
                </div>
              </div>
            </div>
        </div>